### ISSUE TITLE
Loading Pdf from database

### ISSUE THREAD

**Issue by allenvpn312** [alejandro-du/pdf-browser#3]
Hi Alejandro,

Does the add on work for instances where the pdf file is retrieved from the database rather than from upload?

The following code opens up the file system save as dialog when I attempt to display it.

`InputStream is = new ByteArrayInputStream(report.getPdfForm());
StreamResource resource = new StreamResource("blah", () -> is);
				
viewer = new PdfBrowserViewer(resource);
pdfViewer.add(viewer);`

Thanks

**Comment by alejandro-du** [comment]
Hi, yes. But let's use the issue tracker for reporting issues with the component instead of questions. For questions let's use the forum. Thanks!
