### ISSUE TITLE
flow-build-info.json shoudn't be included in JAR

### ISSUE THREAD

**Issue by integrigy** [alejandro-du/pdf-browser#4]
Need to exclude flow-build-info.json from JAR file otherwise due to vaadin/flow#6405 the error  "java.lang.IllegalStateException: Running project in development mode with no access to folder xxxxx" occurs with Vaadin 14.0.4+.  This will be fixed in vaadin/flow#6616.

Same fix as in alejandro-du/crudui#56.

**Comment by alejandro-du** [comment]
This should be fixed now. Let me know if it's still an issue. Thanks.
