### ISSUE TITLE
Problem with @lrnwebcomponents/pdf-browser-viewer version

### ISSUE THREAD

**Issue by mlopezFC** [alejandro-du/pdf-browser#8]
I tried it with the latest Vaadin version and I got this error:

`Failed to execute 'define' on 'CustomElementRegistry': the name "dom-module" has already been used with this registry`

I thought it could be a problem related to different polymer versions, so I changed [this line](https://github.com/alejandro-du/pdf-browser/blob/ada26b0060e865f36ab3d6b37d28c0780ce5c7a6/src/main/java/org/vaadin/alejandro/PdfBrowserViewer.java#L15) for the following (basically pinned the 2.1.4 version):

`@NpmPackage(value = "@lrnwebcomponents/pdf-browser-viewer", version = "2.1.4")`

And it worked.

**Comment by alejandro-du** [comment]
Thanks for reporting and for the solution. I'll take a look at it soon.
